language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: CVsFEdkoqQOxfyuHW6ldk5z+PCIhFKFmiyDmutGc6OwKpd3QiVg8rMYOVdfFN/UHbCgY1cI8/yaM2GHoZNxN4oOjKbNI15aLsjeSsJk4ICa5l0sMyCdOqyhFRcpWGZaofaIceFk3whEpblgPR5KEQqx7HgJa27mE6+ttXrzBDXQ=
  - secure: YyTe+s0WBTOMgnYP6i7zbr+IIa4MqPVOdVtZgYmDo1jBGefAfStLgDCvYgLzzA+J1vJLqalW+dXPzDgpnCG3bzFqxOIYKrj6n1bb3hfHrzm4KNJiScFEipHjz0UHBK5ICGc1k4bAZwHkbNC7wObBnZAhXbHJPjYgukP4PGp8hVU=
